name: learning
on: workflow_dispatch
jobs:
  learning:
   runs-on: ubuntu-latest
   steps:
     - name: testing
       id: we
       run: echo "name=My name is kanchan" >> $GITHUB_OUTPUT
     - name: calling
       run: echo "Your name is ${{ steps.we.outputs.name}}"
        
